#!/usr/bin/env python

import rospy
import tf2_ros
from geometry_msgs.msg import TransformStamped, PoseStamped

POSE_TOPIC="/pose"
BASE_LINK="base_link"
MAP="/map"

def pose_cb(data):
    pose = data.pose
    br = tf2_ros.TransformBroadcaster()
    trans = TransformStamped()
    trans.child_frame_id = BASE_LINK
    trans.header.stamp = data.header.stamp
    trans.header.frame_id = MAP
    trans.transform.translation = pose.position
    trans.transform.rotation = pose.orientation
    br.sendTransform(trans)

if __name__ == "__main__":
    rospy.init_node("map_link_broadcaster")

    sub = rospy.Subscriber(POSE_TOPIC, PoseStamped, pose_cb)
    rospy.spin()
